server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://rbty.fun:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Tuzhiyong432922
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

  data:
    mongodb:
      host: rbty.fun
      port: 27017
      database: mall-port
      username: admin
      password: Tuzhiyong432922
      authentication-database: admin

  redis:
    host: rbty.fun # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: Tuzhiyong432922 # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

  rabbitmq:
    host: rbty.fun
    port: 5672
    virtual-host: /
    username: admin
    password: Tuzhiyong432922

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: debug

logstash:
  host: logstash

